version: 2

init: &init
  docker:
    - image: docksal/ci-agent:php
  working_directory: /home/agent/build

run-envvars: &run-envvars
  name: Configuring build environment
  command: |
    echo 'source build-env' > $BASH_ENV

jobs:
  build-sandbox:
    <<: *init
    steps:
      - run:
          <<: *run-envvars

  build:
    <<: *init
    steps:
      - run:
          <<: *run-envvars
      - checkout
      - run:
          name: Build sandbox
          command: |
           source build-env
           sandbox-init

  deploy-to-production:
    <<: *init
    steps:
      - run:
          <<: *run-envvars
      - run:
          name: Deploying to Production
          command: |
           echo "Server IP"
           build-exec "curl ifconfig.me"
           build-exec "pwd"
           echo "\n"
           source build-env
           echo -e "Removing files and folders that should not be committed to Production...\n"
           build-exec "xargs rm -rf < .pantheon_ignored"
           echo -e "Removing sandbox container and files...\n"
           build-exec "fin project remove && rm -rf ${REMOTE_BUILD_DIR}"

workflows:
  version: 2
  ivo-workflow:
    jobs:
      - build:
          context: org-ivo

      - build-sandbox:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master

      - deploy-to-production:
          requires:
            - build
          context: org-ivo
          filters:
            branches:
              only:
                - master
