version: 2

init: &init
  docker:
    - image: docksal/ci-agent:php
  working_directory: /home/agent/build

run-envvars: &run-envvars
  name: Configuring build environment
  command: |
    echo 'source build-env' > $BASH_ENV

jobs:
  build:
    <<: *init
    steps:
      - run:
          <<: *run-envvars
      - checkout
      - run:
          name: Build sandbox
          command: |
            source build-env
            sandbox-init

  sandbox:
    <<: *init
    steps:
      - run:
          <<: *run-envvars

  deploy:
    <<: *init
    steps:
      - run:
          <<: *run-envvars
      - attach_workspace:
          at: /home/agent
      - run: echo $PRIVATE_KEY | base64 -d > /home/agent/.ssh/id_rsa
      - run:
          name: Deploying to Production
          command: |
            source build-env
            build-exec  "scp -r ${MASTER_DIR} ${SSH_ADD}"
            echo -e "Removing files and folders that should not be committed to Production...\n"
            build-exec "xargs rm -rf < .pantheon_ignored"
            echo -e "Removing sandbox container and files...\n"
            build-exec "fin p remove && rm -rf ${REMOTE_BUILD_DIR}"


workflows:
  version: 2
  ivo-workflow:
    jobs:
      - build:
          context: org-ivo

      - sandbox:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master

      - deploy:
          requires:
            - build
          context: org-ivo
          filters:
            branches:
              only:
                - master
